In [1]:
import pandas as pd
from datasets import load_dataset  # Requires transformers>=4.51.0
from sentence_transformers import SentenceTransformer
import numpy as np

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
ds = load_dataset("rohitsaxena/MovieSum")

Repo card metadata block was not found. Setting CardData to empty.


In [3]:
train = ds["train"]
validation = ds["validation"]
test = ds["test"]
dftr = pd.DataFrame(train)
dfva = pd.DataFrame(validation)
dfte = pd.DataFrame(test)

In [4]:
df = pd.concat([dftr, dfva, dfte])
df

movie_name     imdb_id  \
0                         8MM_1999   tt0134273   
1               The Iron Lady_2011   tt1007029   
2               Adventureland_2009   tt1091722   
3                    Napoleon_2023  tt13287846   
4    Kubo and the Two Strings_2016   tt4302938   
..                             ...         ...   
195      Terminator Salvation_2009   tt0438488   
196         Collateral Damage_2002   tt0233469   
197              Wonder Woman_2017   tt0451279   
198                Flatliners_2017   tt2039338   
199                   Vacancy_2007   tt0452702   

                                                script  \
0    <script>\n  <scene>\n    <stage_direction>INT....   
1    <script>\n  <scene>\n    <stage_direction>INT....   
2    <script>\n  <scene>\n    <scene_description>Ad...   
3    <script>\n  <scene>\n    <character>NAPOLEON</...   
4    <script>\n  <scene>\n    <character>KUBO</char...   
..                                                 ...   
195  <script>\n  <scene>\n    <stage_direction>INT....   
196  <script>\n  <scene>\n    <stage_direction>INT....   
197  <script>\n  <scene>\n    <scene_description>FA...   
198  <script>\n  <scene>\n    <character>FLATLINERS...   
199  <script>\n  <scene>\n    <character>VACANCY</c...   

                                               summary  
0    Private investigator Tom Welles is contacted b...  
1    In flashbacks, the audience is shown a young M...  
2    In 1987, James Brennan plans to have a summer ...  
3    In 1793, amid the French Revolution, young arm...  
4    In feudal Japan, a 12-year-old boy with only o...  
..                                                 ...  
195  In 2003, Dr. Serena Kogan of Cyberdyne Systems...  
196  A bomb detonates in the plaza of the Colombian...  
197  In present-day Paris, Diana Prince receives a ...  
198  Courtney is a medical student who is obsessed ...  
199  On their way home from a family party, David a...  

[2200 rows x 4 columns]

In [5]:
df2 = df.reset_index().drop("index", axis=1)
df2.head(30)

movie_name     imdb_id  \
0                                     8MM_1999   tt0134273   
1                           The Iron Lady_2011   tt1007029   
2                           Adventureland_2009   tt1091722   
3                                Napoleon_2023  tt13287846   
4                Kubo and the Two Strings_2016   tt4302938   
5                          The Woman King_2022   tt8093700   
6                           What They Had_2018   tt6662736   
7                    Synecdoche, New York_2008   tt0383028   
8                         Black Christmas_2006   tt0454082   
9                                Superbad_2007   tt0829482   
10                              The Guest_2014   tt2980592   
11            Even Cowgirls Get the Blues_1993   tt0106834   
12                              Backdraft_1991   tt0101393   
13                             Maleficent_2014   tt1587310   
14                     All the King's Men_2006   tt0405676   
15  I Still Know What You Did Last Summer_1998   tt0130018   
16                              Nine Days_2020  tt10451852   
17              Hangin' with the Homeboys_1991   tt0101998   
18                                  Selma_2014   tt1020072   
19                          All About Eve_1950   tt0042192   
20                             Just Mercy_2019   tt4916630   
21                     Jingle All the Way_1996   tt0116705   
22                       Punch-Drunk Love_2002   tt0272338   
23                             The Batman_2022   tt1877830   
24                                  Mimic_1997   tt0119675   
25                         Animal Kingdom_2010   tt1313092   
26                            End of Days_1999   tt0146675   
27                      Fantastic Mr. Fox_2009   tt0432283   
28                                Platoon_1986   tt0091763   
29                                   Rush_2013   tt1979320   

                                               script  \
0   <script>\n  <scene>\n    <stage_direction>INT....   
1   <script>\n  <scene>\n    <stage_direction>INT....   
2   <script>\n  <scene>\n    <scene_description>Ad...   
3   <script>\n  <scene>\n    <character>NAPOLEON</...   
4   <script>\n  <scene>\n    <character>KUBO</char...   
5   <script>\n  <scene>\n    <character>THE WOMAN ...   
6   <script>\n  <scene>\n    <character>WHAT THEY ...   
7   <script>\n  <scene>\n    <scene_description>SY...   
8   <script>\n  <scene>\n    <scene_description>BI...   
9   <script>\n  <scene>\n    <stage_direction>SUPE...   
10  <script>\n  <scene>\n    <scene_description>TH...   
11  <script>\n  <scene>\n    <stage_direction>INT....   
12  <script>\n  <scene>\n    <stage_direction>INT....   
13  <script>\n  <scene>\n    <scene_description>Ma...   
14  <script>\n  <scene>\n    <character>ALL THE KI...   
15  <script>\n  <scene>\n    <stage_direction>INT....   
16  <script>\n  <scene>\n    <scene_description>NI...   
17  <script>\n  <scene>\n    <scene_description>HA...   
18  <script>\n  <scene>\n    <character>SELMA</cha...   
19  <script>\n  <scene>\n    <stage_direction>INT....   
20  <script>\n  <scene>\n    <scene_description>Re...   
21  <script>\n  <scene>\n    <character>J:IN:&lt;;...   
22  <script>\n  <scene>\n    <stage_direction>INT....   
23  <script>\n  <scene>\n    <character>THE BATMAN...   
24  <script>\n  <scene>\n    <character>M I M I C<...   
25  <script>\n  <scene>\n    <scene_description>AN...   
26  <script>\n  <scene>\n    <scene_description>Wr...   
27  <script>\n  <scene>\n    <scene_description>FA...   
28  <script>\n  <scene>\n    <stage_direction>Plat...   
29  <script>\n  <scene>\n    <character>RUSH</char...   

                                              summary  
0   Private investigator Tom Welles is contacted b...  
1   In flashbacks, the audience is shown a young M...  
2   In 1987, James Brennan plans to have a summer ...  
3   In 1793, amid the French Revolution, young arm...  
4   In feudal Japan, a 12-year-old boy with only o...  
5   In th

In [6]:
# Load the model
model = SentenceTransformer("Qwen/Qwen3-Embedding-0.6B")  # maybe try reranker as well?

# We recommend enabling flash_attention_2 for better acceleration and memory saving,
# together with setting `padding_side` to "left":
# model = SentenceTransformer(
#     "Qwen/Qwen3-Embedding-0.6B",
#     model_kwargs={"attn_implementation": "flash_attention_2", "device_map": "auto"},
#     tokenizer_kwargs={"padding_side": "left"},
# )


In [7]:
MODELPROMPT = "Instruct: Given a movie search query, retrieve relevant movies that match the query in mood, genre, and plot\nQuery:"

In [8]:
# The queries and documents to embed
queries = [
    "I want a sci-fi movie where Earth is destroyed and other planets are explored. It should involve wormholes and time dilation. The main character should use black holes to communicate with the past.",
    "I want a sci-fi movie where the world is a simulation. The main character is a programmer who one day is presented with a choice to remain in the simulation or break free from it.",
    "Private investigator Tom Welles is contacted by Daniel Longdale, attorney for wealthy widow Mrs. Christian. While clearing out her recently deceased husband's safe, she and Longdale find an 8mm movie which appears to depict a real murder of a girl, but Mrs. Christian wants to know for certain. Welles is instructed by Longdale and Mrs. Christian not to reproduce the film in any way, and to keep the investigation secret. After looking through missing persons files, Welles discovers the girl is Mary Ann Mathews and visits her mother, Janet, in North Carolina. She allows Welles to search her house, and he finds Mary Ann's diary, in which she says she relocated to Hollywood to become a film star. Mrs. Mathews demands that he find out what happened to her daughter. In Hollywood, aided by adult video store clerk Max California, Welles infiltrates the world of underground fetish pornography. He attempts to find out if snuff films are real, or if anyone was connected to this film, but finds no evidence that a snuff film industry exists. Contact with sleazy talent scout Eddie Poole leads Welles and Max to director Dino Velvet; Velvet's violently pornographic films often feature a masked man named \"Machine\", who not only brutalizes and tortures women, but also resembles the man featured in Christian's snuff film. To gain more evidence, Welles and California travel to New York and pose as clients interested in commissioning a hardcore BDSM film to be directed by Velvet and starring Machine. Velvet appears to agree, and schedules a meeting. The meeting turns out to be an ambush, as Longdale and Poole appear and hold Welles at gunpoint. The film is revealed as authentic; Mr. Christian contacted Longdale to procure a snuff film, and being unable to find one, Longdale commissioned Velvet and Poole to make one. Velvet and Machine produce a bound and beaten Max, whom they abducted to force Welles to bring them the only surviving copy of the film. As Longdale and Welles go to Welles's car to retrieve the film, Longdale admits he never thought Welles would get as far as he did, and just wanted to placate Mrs. Christian with the investigation. Once Welles delivers the film, Longdale and Velvet burn it and kill Max. As they are about to kill Welles, he confesses Mr. Christian paid $1 million for the film; Velvet, Poole, and Machine received $50,000 and Longdale kept the major portion. In an ensuing fight, Velvet and Longdale are killed; Welles wounds Machine and escapes. Subsequently, he informs Mrs. Christian regarding his findings and recommends she contact the police. Arriving at her estate, he is shocked to hear that she committed suicide immediately after receiving the phone call and notices envelopes that she left behind both for the Mathews family and for him; his envelope contains the rest of his payment and a note reading, \"Try to forget us.\" He instructs his wife Amy and their infant daughter Cindy to escape from the impending danger to a secret location, donating his half of the money to her. Deciding to avenge Mary Ann's death by killing the remaining people involved, Welles returns to Hollywood, tracks down Poole, and takes him to the shooting location, but stops short of killing him. He calls Mrs. Mathews to tell her about her daughter and asks for her permission to punish those responsible. Mrs. Mathews breaks down once presented with the truth, but affirms that she loved her daughter and permits him to proceed. With that, Welles pistol whips Poole to death with his gun, burning his body and the pornography from his car. He then attacks Machine at his home and unmasks him, revealing a bespectacled man named George Anthony Higgins, who admits that his sadistic actions are simply done out of pleasure, and are unrelated to any personal trauma. Welles then kills him in the ensuing struggle. After returning to his family, Welles breaks down in front of Amy, attempting to process all the evil things that he had witnessed throughout the investigation. Months later, he receives a letter from Mrs. Mathews, thanking him and relating her gratitude for the fact that, despite everything, they were the only two people who really cared about Mary Ann.",
]
summaries = df2["summary"]
summaries = list(summaries)


In [18]:
# Encode the queries and documents. Note that queries benefit from using a prompt
# Here we use the prompt called "query" stored under `model.prompts`, but you can
# also pass your own prompt via the `prompt` argument
query_embeddings = model.encode(
    queries,
    prompt=MODELPROMPT,
)

summaries_embeddings = np.load("../data/moviesum/summaries_embeddings2.npy")
# import pickle

# with open("../data/moviesum/summaries_embeddings", "rb") as p:
#    summaries_embeddings = np.load(p, allow_pickle=True)

In [19]:
summaries_embeddings

array([[-0.0079725 , -0.03835354, -0.00583044, ...,  0.02077697,
         0.03271362, -0.04445053],
       [-0.0157134 ,  0.05088204, -0.0096964 , ..., -0.02301508,
         0.00084189, -0.01440106],
       [ 0.00358987, -0.00554255, -0.01074963, ..., -0.05948191,
        -0.04277627,  0.01209996],
       ...,
       [ 0.0616278 ,  0.07584508, -0.0094791 , ...,  0.00836658,
         0.01255995,  0.00195015],
       [ 0.01125546,  0.03021189, -0.01118757, ..., -0.00647854,
         0.00766611, -0.02217219],
       [-0.0221491 , -0.01895529, -0.01008042, ...,  0.01675951,
         0.00575323, -0.01500033]], dtype=float32)

In [20]:
summaries_embeddings.shape

(2200, 1024)

In [22]:
# Compute the (cosine) similarity between the query and document embeddings
similarity = model.similarity(query_embeddings, summaries_embeddings)
print(similarity)
# tensor([[0.7646, 0.1414],
#         [0.1355, 0.6000]])

tensor([[0.2202, 0.1808, 0.1471,  ..., 0.2895, 0.2934, 0.2220],
        [0.2159, 0.1909, 0.2592,  ..., 0.2622, 0.3417, 0.2665],
        [0.8681, 0.2444, 0.3063,  ..., 0.2830, 0.3254, 0.4093]])


In [29]:
query_embedding_pairs = zip(query_embeddings, queries)
list(query_embedding_pairs)

[(array([ 0.04100367,  0.03815329, -0.00650854, ..., -0.0396319 ,
          0.03308045, -0.02063533], dtype=float32),
  'I want a sci-fi movie where Earth is destroyed and other planets are explored. It should involve wormholes and time dilation. The main character should use black holes to communicate with the past.'),
 (array([-0.00085721, -0.0293558 , -0.00227461, ...,  0.01480684,
         -0.02188967,  0.0057292 ], dtype=float32),
  'I want a sci-fi movie where the world is a simulation. The main character is a programmer who one day is presented with a choice to remain in the simulation or break free from it.'),
 (array([ 0.00262811, -0.05756217, -0.00468105, ...,  0.01996833,
          0.0209661 , -0.02286854], dtype=float32),
  'Private investigator Tom Welles is contacted by Daniel Longdale, attorney for wealthy widow Mrs. Christian. While clearing out her recently deceased husband\'s safe, she and Longdale find an 8mm movie which appears to depict a real murder of a girl, but

In [30]:
best_matches = similarity.argmax(1)
best_matches

tensor([1661,  823,    0])

In [44]:
df2.iloc[best_matches.tolist(), [0, 1]]

movie_name    imdb_id
1661  Interstellar_2014  tt0816692
823     The Matrix_1999  tt0133093
0              8MM_1999  tt0134273

['movie_name', 'imdb_id']

In [46]:
df2

movie_name     imdb_id  \
0                          8MM_1999   tt0134273   
1                The Iron Lady_2011   tt1007029   
2                Adventureland_2009   tt1091722   
3                     Napoleon_2023  tt13287846   
4     Kubo and the Two Strings_2016   tt4302938   
...                             ...         ...   
2195      Terminator Salvation_2009   tt0438488   
2196         Collateral Damage_2002   tt0233469   
2197              Wonder Woman_2017   tt0451279   
2198                Flatliners_2017   tt2039338   
2199                   Vacancy_2007   tt0452702   

                                                 script  \
0     <script>\n  <scene>\n    <stage_direction>INT....   
1     <script>\n  <scene>\n    <stage_direction>INT....   
2     <script>\n  <scene>\n    <scene_description>Ad...   
3     <script>\n  <scene>\n    <character>NAPOLEON</...   
4     <script>\n  <scene>\n    <character>KUBO</char...   
...                                                 ...   
2195  <script>\n  <scene>\n    <stage_direction>INT....   
2196  <script>\n  <scene>\n    <stage_direction>INT....   
2197  <script>\n  <scene>\n    <scene_description>FA...   
2198  <script>\n  <scene>\n    <character>FLATLINERS...   
2199  <script>\n  <scene>\n    <character>VACANCY</c...   

                                                summary  
0     Private investigator Tom Welles is contacted b...  
1     In flashbacks, the audience is shown a young M...  
2     In 1987, James Brennan plans to have a summer ...  
3     In 1793, amid the French Revolution, young arm...  
4     In feudal Japan, a 12-year-old boy with only o...  
...                                                 ...  
2195  In 2003, Dr. Serena Kogan of Cyberdyne Systems...  
2196  A bomb detonates in the plaza of the Colombian...  
2197  In present-day Paris, Diana Prince receives a ...  
2198  Courtney is a medical student who is obsessed ...  
2199  On their way home from a family party, David a...  

[2200 rows x 4 columns]

In [89]:
onedse = [x for x in summaries_embeddings]
# onedse.shape
# onedse.reshape((2200,))
# onedse = pd.Series(onedse)

onedse

[array([-0.0079725 , -0.03835354, -0.00583044, ...,  0.02077697,
         0.03271362, -0.04445053], dtype=float32),
 array([-0.0157134 ,  0.05088204, -0.0096964 , ..., -0.02301508,
         0.00084189, -0.01440106], dtype=float32),
 array([ 0.00358987, -0.00554255, -0.01074963, ..., -0.05948191,
        -0.04277627,  0.01209996], dtype=float32),
 array([-0.00473548, -0.00882306, -0.0096338 , ..., -0.00624614,
        -0.03315658, -0.03732176], dtype=float32),
 array([-0.00978753, -0.02538656, -0.01113862, ...,  0.02001623,
         0.036536  ,  0.02148507], dtype=float32),
 array([ 0.05122995, -0.03473575, -0.01148079, ...,  0.00683096,
        -0.00870687, -0.06386983], dtype=float32),
 array([-0.0575964 ,  0.10421418, -0.00519611, ..., -0.03807385,
        -0.02487457, -0.00138899], dtype=float32),
 array([ 0.01926129,  0.01350535, -0.00965736, ...,  0.0028698 ,
        -0.04522905, -0.01300552], dtype=float32),
 array([ 0.00896564, -0.01568128, -0.00922665, ..., -0.04840872,
       

In [90]:
df2["summary_embedding"] = onedse

In [91]:
df2

movie_name     imdb_id  \
0                          8MM_1999   tt0134273   
1                The Iron Lady_2011   tt1007029   
2                Adventureland_2009   tt1091722   
3                     Napoleon_2023  tt13287846   
4     Kubo and the Two Strings_2016   tt4302938   
...                             ...         ...   
2195      Terminator Salvation_2009   tt0438488   
2196         Collateral Damage_2002   tt0233469   
2197              Wonder Woman_2017   tt0451279   
2198                Flatliners_2017   tt2039338   
2199                   Vacancy_2007   tt0452702   

                                                 script  \
0     <script>\n  <scene>\n    <stage_direction>INT....   
1     <script>\n  <scene>\n    <stage_direction>INT....   
2     <script>\n  <scene>\n    <scene_description>Ad...   
3     <script>\n  <scene>\n    <character>NAPOLEON</...   
4     <script>\n  <scene>\n    <character>KUBO</char...   
...                                                 ...   
2195  <script>\n  <scene>\n    <stage_direction>INT....   
2196  <script>\n  <scene>\n    <stage_direction>INT....   
2197  <script>\n  <scene>\n    <scene_description>FA...   
2198  <script>\n  <scene>\n    <character>FLATLINERS...   
2199  <script>\n  <scene>\n    <character>VACANCY</c...   

                                                summary  \
0     Private investigator Tom Welles is contacted b...   
1     In flashbacks, the audience is shown a young M...   
2     In 1987, James Brennan plans to have a summer ...   
3     In 1793, amid the French Revolution, young arm...   
4     In feudal Japan, a 12-year-old boy with only o...   
...                                                 ...   
2195  In 2003, Dr. Serena Kogan of Cyberdyne Systems...   
2196  A bomb detonates in the plaza of the Colombian...   
2197  In present-day Paris, Diana Prince receives a ...   
2198  Courtney is a medical student who is obsessed ...   
2199  On their way home from a family party, David a...   

                                      summary_embedding  
0     [-0.0079724975, -0.038353536, -0.0058304435, 0...  
1     [-0.015713397, 0.050882038, -0.009696398, 0.04...  
2     [0.003589871, -0.0055425544, -0.010749631, 0.0...  
3     [-0.0047354815, -0.008823062, -0.009633801, -0...  
4     [-0.009787532, -0.025386559, -0.011138619, -0....  
...                                                 ...  
2195  [0.054458164, -0.0010868734, -0.011360162, 0.0...  
2196  [0.03867368, -0.0066833715, -0.0106056705, 0.0...  
2197  [0.0616278, 0.07584508, -0.009479098, 0.033249...  
2198  [0.011255455, 0.030211888, -0.01118757, 0.0929...  
2199  [-0.022149099, -0.018955287, -0.010080418, 0.0...  

[2200 rows x 5 columns]

In [106]:
np.stack(df2["summary_embedding"].to_numpy()) == summaries_embeddings

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [95]:
summaries_embeddings

array([[-0.0079725 , -0.03835354, -0.00583044, ...,  0.02077697,
         0.03271362, -0.04445053],
       [-0.0157134 ,  0.05088204, -0.0096964 , ..., -0.02301508,
         0.00084189, -0.01440106],
       [ 0.00358987, -0.00554255, -0.01074963, ..., -0.05948191,
        -0.04277627,  0.01209996],
       ...,
       [ 0.0616278 ,  0.07584508, -0.0094791 , ...,  0.00836658,
         0.01255995,  0.00195015],
       [ 0.01125546,  0.03021189, -0.01118757, ..., -0.00647854,
         0.00766611, -0.02217219],
       [-0.0221491 , -0.01895529, -0.01008042, ...,  0.01675951,
         0.00575323, -0.01500033]], dtype=float32)